name: 'Syrinx'
description: 'OSR e dintorni'
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /kasper
domain_name: "http://zeruhur.space"
google_analytics: "G-K7HZWVR5FP"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: 'zeruhur'

# Disqus config
disqus-shortname: "adasperaludens"
