# Site settings
title:       Syrinx
email:       robertobisceglie@gmail.com
author:      zeruhur
description: "OSR e dintorni"
baseurl:     "/syrinx"
url:         "https://zeruhur.space"
date_format: "%d/%m/%Y"
header_pages:
 - about.md
 - contact.html

google_analytics:

# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true

# Preview image for social media aka og:image and twitter:image
post_preview_image: false

# Disqus post comments
disqus_shortname: adasperaludens

# Social icons
github_username: zeruhur
twitter_username: zeruhur
linkedin_username: 
dev_username: 

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: true
share_reddit: true
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Nuovi'
    older: 'Vecchi'
  share_buttons:
    text:         'Condividi:'
    facebook:     'Condividi su Facebook'
    twitter:      'Condividi su Twitter'
    googleplus:   'Condividi su Google+'
    linkedin:     'Condividi su LinkedIn'
    digg:         'Condividi su Digg'
    tumblr:       'Condividi su Tumblr'
    reddit:       'Condividi su Reddit'
    stumbleupon:  'Condividi su StumbleUpon'
    hackernews:   'Condividi su Hacker News'
  post:
    updated:        'Aggiornato'
    minute_read:    'minuti di lettura'
    related_posts:  'Post correlati'
    post_footer:    'Lorem ipsum'
  index:
    coming_soon: 'Coming soon...'
  og_locale: 'it'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: /:categories/:year/:month/:day/:title/
paginate:     5
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor