# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'adasperaludens'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-4M6BX297FY'

menu:
- {name: 'Chi sono', path: 'menu', url: 'about.html'}
- {name: 'Archivio', path: 'menu', url: 'archive.html'}
- {name: 'Dove Trovarmi', path: 'menu', url: 'https://wheretofind.me/@zeruhur'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'github', link: 'https://www.github.com/zeruhur'}
- {icon: 'telegram', link: 'https://t.me/zeruhur'}
# - {icon: 'twitter', link: 'https://twitter.com/zeruhur'}
# - {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
# - {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Condividi!'

related_posts: 'Potrebbe anche piacerti:'

post_date_prefix: 'Scritto il'
